theme: jekyll-theme-merlot
plugins:
  - jekyll-relative-links
google_analytics: UA-141696430-1
relative_links:
  enabled: true
  collections: true
include:
  - About.md
  - README.md
  - Contact.md
  - Work.md
